SCREEN_SIZE = (1280,720)
DRAW_SCREEN_SIZE = (480,320)
FRAMERATE = 60
GRAVITY = 1
END_TIME = 150

##player
JUMP_SPEED = 2
MAX_JUMP = 90                       ## Frame time
PLAYER_SPEED = 2
PLAYER_HP = 3

## enemy
ENEMY_SPEED = 1
CREATE_ENEMY_RATIO = 100
ENEMY_MOVE_RATIO = 40
BOMB_ANIMATION_COOLDOWN = 1000
BOMB_DETONATION_TIME = 6000
BOOM_ANIMATION_COOLDOWN = 500


## Bonus
BONUS_SPEED = 3
CREATE_BONUS_RATIO = 500
BONUS_MOVE_RATIO = ENEMY_MOVE_RATIO

## Tile
CREATE_TILE_RATIO = 2000
TILE_LIFE_TIME = 20000



# https://www.youtube.com/watch?v=nXOVcOBqFwM
# PyGame Beginner Tutorial in Python - Loading Spritesheets