SCREEN_SIZE = (1280,720)
DRAW_SCREEN_SIZE = (480,320)
FRAMERATE = 60
PLAYER_SPEED = 2
GRAVITY = 1
JUMP_SPEED = 2
MAX_JUMP = 90                       ## Frame time


## enemy
ENEMY_SPEED = 1
CREATE_ENEMY_RATIO = 100
ENEMY_MOVE_RATIO = 40

## Bonus
BONUS_SPEED = 3
CREATE_BONUS_RATIO = 500
BONUS_MOVE_RATIO = ENEMY_MOVE_RATIO